nginx:
    build: .
    ports:
        - "8050:80"
    links:
        - fpm
        - mysql
fpm:
    image: php:7.2-fpm
    volumes:
        - ./:/acme-graphql

mysql:
    image: mysql:5.7
    environment:
        - DB_HOST=mysql
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=acme_graphql
